# -*- mode: ruby -*-
# vi: set ft=ruby :
servers = {
  "Productor" => { :ip => "192.168.56.2", :cpus => 1, :mem => 1024, :ssh_port=>2222 },
  "BrokerRabbitmq" => { :ip => "192.168.56.3", :cpus => 1, :mem => 1024, :ssh_port=>2200 },
  "Consumidor1" => { :ip => "192.168.56.4", :cpus => 1, :mem => 1024, :ssh_port=>2200 },
  "Consumidor2" => { :ip => "192.168.56.5", :cpus => 1, :mem => 1024, :ssh_port=>2200} 
}
Vagrant.configure("2") do |config|
  servers.each_with_index do |(hostname, info), index|
     config.vm.define hostname do |cfg|
       cfg.vm.provider :virtualbox do |vb, override| 
         config.vm.box = "bento/ubuntu-18.04"
         override.vm.network "private_network", ip: "#{info[:ip]}"
         override.vm.network "forwarded_port", guest: 22, host:"#{info[:ssh_port]}", id: "ssh", auto_correct: true
         override.vm.hostname = hostname
         vb.name = hostname
         vb.name = hostname
       end
     end
  end
  #Aprovisionamiento de los servidores
    config.vm.provision "ansible" do |ansible|
            ansible.inventory_path = 'hosts'
            ansible.verbose = 'vvv'
            ansible.playbook = 'playbooks/servers.yml'
            
    end
end
